
name: Deploy Demo Site

on:
  workflow_dispatch: # disabled — demo deployment not used in this fork

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
    - name: pull changes
      uses: appleboy/ssh-action@1530429296e979861824d74fb800013190b5dee0  # master (2026-04-29)
      with:
        host: ${{ secrets.DEMO_HOST }}
        username: ${{ secrets.DEMO_SSH_USERNAME }}
        key: ${{ secrets.DEMO_SSH_KEY }}
        port: ${{ secrets.DEMO_SSH_PORT }}
        script: |
          cd velvet/
          git pull
          npm install --production
          pm2 restart all
